version: "3"

networks:
  overlay-network:
    external:
      name: overlay-network
  logging:
    external:
      name: logging

services:

  elasticsearch:
    image: elasticsearch:5.3.2
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    environment:
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
      ES_JAVA_OPTS: "-Xmx256m -Xms256m -Des.enforce.bootstrap.checks=true"
    networks:
      - overlay-network
      - logging
  
  fluentbit:
    image: taufiq12/fluent-bit:simple
    ports:
      - 24224:24224
      - 24224:24224/udp
    depends_on:
      - elasticsearch
    networks:
      - overlay-network
      - logging
  
  kibana:
    image: kibana:5.3.2
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      XPACK_SECURITY_ENABLED: 'false'
      XPACK_MONITORING_ENABLED: 'false'
    networks:
      - overlay-network
      - logging

volumes:
  elastic:
    driver: local