version: "3"

networks:
  overlay-network:
    external:
      name: overlay-network
  logging:
    external:
      name: logging

services:

  elasticsearch:
    image: elasticsearch:7.3.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-nodes
    networks:
      - overlay-network
      - logging
  
  fluentbit:
    image: taufiq12/fluent-bit:simple
    ports:
      - 24224:24224
      - 24224:24224/udp
    depends_on:
      - elasticsearch
    networks:
      - overlay-network
      - logging
  
  kibana:
    image: kibana:7.3.0
    ports:
      - "5601:5601"
    networks:
      - overlay-network
      - logging