---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  
  tasks:
    - name: Install epel-release
      yum:
        name: epel-release
        state: latest

    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
    
    - name: Install net tools
      yum:
        name: net-tools
        state: latest
    
    - name: Install Python pip
      yum:
        name: python-pip
    
    - name: Upgrade pip
      pip:
        name: pip
        extra_args: --upgrade
    
    - name: Open Port
      firewalld:
        port: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - 2376/tcp
        - 2377/tcp
        - 7946/tcp
        - 7946/udp
        - 4789/tcp
        - 80/tcp
        - 5001/tcp
        - 9200/tcp
        - 9300/tcp
        - 24224/tcp
        - 24224/udp
        - 5601/tcp
        - 9090/tcp
        - 3000/tcp
        - 8080/tcp
        - 8081/tcp
    
    - name: Install docker_swarm python requirements
      pip:
        name: jsondiff,pyyaml