---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  
  tasks:
  - name: Install Device Mapper & LVM2
    yum:
      name: "{{ packages }}"
      state: latest
    vars:
      packages:
        - device-mapper-persistent-data
        - lvm2
  
  - name: Add Docker Repository
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
  
  - name: Install Docker Container Engine
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - docker-ce-{{ docker_version }}.*
        - docker-ce-cli-{{ docker_version }}.*
        - containerd.io
          
  - name: Install python-docker
    yum:
      name: python-docker
      state: present
  
  - name: Install Docker Compose module
    pip:
      name: docker-compose
      state: latest

  - name: Enable and Run Docker
    systemd:
      name: docker
      enabled: yes
      state: started

  - name: Setting sebool container_manage_cgroup
    seboolean:
      name: container_manage_cgroup
      state: yes
      persistent: yes